# Generated by Django 4.1.7 on 2023-03-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not want to disclose', 'Do not want to disclose')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='qualification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='skills',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
