# Generated by Django 4.1.7 on 2023-03-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0003_alter_userinfo_profile_pic_jobproviderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='firstname',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lastname',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
