# Generated by Django 4.1.7 on 2023-03-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0004_userinfo_firstname_userinfo_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='linked_id',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
