# Generated by Django 4.1.7 on 2023-03-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0005_remove_userinfo_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='resume',
            field=models.FileField(null=True, upload_to='media/resume'),
        ),
    ]
