# Generated by Django 4.1.7 on 2023-03-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0006_remove_userinfo_profile_pic_userinfo_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/resume'),
        ),
    ]
