# Generated by Django 4.1.7 on 2023-03-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0007_alter_userinfo_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='resume',
            field=models.FileField(null=True, upload_to='media/resume'),
        ),
    ]
