# Generated by Django 4.1.7 on 2023-03-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0010_userinfo_dob_alter_jobproviderinfo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobproviderinfo',
            name='project_file',
            field=models.FileField(blank=True, upload_to='project_file'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='pic'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
