# Generated by Django 4.1.7 on 2023-03-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0011_jobproviderinfo_project_file_userinfo_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
